"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import ContractorHeader from "@/app/components/ContractorHeader";
import ErrorMessage from "@/app/components/ErrorMessage";
import PageLoader from "@/app/components/PageLoader";

interface Estimate {
  estimateId: string;
  range: {
    min: number;
    max: number;
  };
  costBreakdown: {
    equipment: number;
    labor: number;
    materials: number;
    total: number;
  };
  assumptions: string[];
  createdAt?: string;
}

export default function EstimatesPage() {
  const router = useRouter();
  const [estimates, setEstimates] = useState<Estimate[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    fetch("/api/contractor/estimates")
      .then((res) => {
        if (!res.ok) {
          if (res.status === 401 || res.status === 403) {
            router.push("/contractor/access-denied");
            return null;
          }
          throw new Error("Failed to load estimates");
        }
        return res.json();
      })
      .then((data) => {
        if (data && data.success && data.estimates) {
          // Remove duplicates based on estimateId
          const uniqueEstimates = Array.from(
            new Map(data.estimates.map((est: Estimate) => [est.estimateId, est])).values()
          ) as Estimate[];
          setEstimates(uniqueEstimates);
        }
        setLoading(false);
      })
      .catch((err) => {
        setError(err.message || "Failed to load estimates");
        setLoading(false);
      });
  }, [router]);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const formatDate = (dateString?: string) => {
    if (!dateString) return "Recently";
    try {
      const date = new Date(dateString);
      return new Intl.DateTimeFormat("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
        hour: "numeric",
        minute: "2-digit",
      }).format(date);
    } catch {
      return "Recently";
    }
  };

  const filteredEstimates = estimates.filter((estimate) => {
    if (!searchTerm) return true;
    const search = searchTerm.toLowerCase();
    return (
      estimate.estimateId.toLowerCase().includes(search) ||
      formatCurrency(estimate.range.min).toLowerCase().includes(search) ||
      formatCurrency(estimate.range.max).toLowerCase().includes(search)
    );
  });

  if (loading) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
        <ContractorHeader />
        <PageLoader message="Loading estimates..." />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <ContractorHeader />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">Client Estimates</h1>
              <p className="text-slate-300">
                View and manage all estimates generated by your company
              </p>
            </div>
            <Link
              href="/contractor/c1"
              className="inline-flex items-center gap-2 px-6 py-3 bg-primary-600 text-white font-semibold rounded-xl hover:bg-primary-700 transition-colors cursor-pointer"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
              </svg>
              New Estimate
            </Link>
          </div>

          {/* Search */}
          <div className="mt-6">
            <div className="relative">
              <input
                type="text"
                placeholder="Search estimates by ID or price range..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full px-4 py-3 pl-10 bg-white/10 border border-white/20 rounded-xl text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
              <svg
                className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-6">
            <ErrorMessage message={error} type="error" />
          </div>
        )}

        {/* Estimates List */}
        {filteredEstimates.length === 0 ? (
          <div className="bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 shadow-2xl p-12 text-center">
            <svg
              className="w-20 h-20 text-slate-500 mx-auto mb-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
            <h3 className="text-xl font-semibold text-white mb-2">
              {searchTerm ? "No estimates found" : "No estimates yet"}
            </h3>
            <p className="text-slate-400 mb-6">
              {searchTerm
                ? "Try adjusting your search terms"
                : "Generate your first estimate to get started"}
            </p>
            {!searchTerm && (
              <Link
                href="/contractor/c1"
                className="inline-flex items-center gap-2 px-6 py-3 bg-primary-600 text-white font-semibold rounded-xl hover:bg-primary-700 transition-colors cursor-pointer"
              >
                Create First Estimate
              </Link>
            )}
          </div>
        ) : (
          <div className="grid gap-4">
            {filteredEstimates.map((estimate, index) => (
              <Link
                key={`${estimate.estimateId}-${index}`}
                href={`/contractor/estimates/${estimate.estimateId}`}
                className="block bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 shadow-2xl p-6 hover:bg-white/15 transition-all cursor-pointer"
              >
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-primary-500/20 rounded-xl flex items-center justify-center">
                      <svg
                        className="w-6 h-6 text-primary-300"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                        />
                      </svg>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-white mb-1">
                        Estimate #{estimate.estimateId.slice(0, 8)}
                      </h3>
                      <p className="text-slate-400 text-sm">{formatDate(estimate.createdAt)}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-2xl font-bold text-white mb-1">
                      {formatCurrency(estimate.range.min)} - {formatCurrency(estimate.range.max)}
                    </p>
                    <p className="text-slate-400 text-sm">Price Range</p>
                  </div>
                </div>

                <div className="grid md:grid-cols-4 gap-4 pt-4 border-t border-white/10">
                  <div>
                    <p className="text-slate-400 text-xs mb-1">Equipment</p>
                    <p className="text-white font-semibold">{formatCurrency(estimate.costBreakdown.equipment)}</p>
                  </div>
                  <div>
                    <p className="text-slate-400 text-xs mb-1">Labor</p>
                    <p className="text-white font-semibold">{formatCurrency(estimate.costBreakdown.labor)}</p>
                  </div>
                  <div>
                    <p className="text-slate-400 text-xs mb-1">Materials</p>
                    <p className="text-white font-semibold">{formatCurrency(estimate.costBreakdown.materials)}</p>
                  </div>
                  <div>
                    <p className="text-slate-400 text-xs mb-1">Total</p>
                    <p className="text-primary-300 font-bold">{formatCurrency(estimate.costBreakdown.total)}</p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}

        {/* Stats */}
        {estimates.length > 0 && (
          <div className="mt-8 bg-white/5 rounded-xl p-6 border border-white/10">
            <div className="grid md:grid-cols-3 gap-6 text-center">
              <div>
                <p className="text-3xl font-bold text-white mb-1">{estimates.length}</p>
                <p className="text-slate-400 text-sm">Total Estimates</p>
              </div>
              <div>
                <p className="text-3xl font-bold text-white mb-1">
                  {formatCurrency(
                    estimates.reduce((sum, e) => sum + e.costBreakdown.total, 0) / estimates.length
                  )}
                </p>
                <p className="text-slate-400 text-sm">Average Total</p>
              </div>
              <div>
                <p className="text-3xl font-bold text-white mb-1">
                  {formatCurrency(
                    Math.max(...estimates.map((e) => e.range.max))
                  )}
                </p>
                <p className="text-slate-400 text-sm">Highest Estimate</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}

